user = 'python'
userU = user.upper()
text = 'Предложение из  нескольких   слов'
None1 = None
d = f'Hello, {userU}!'
e = d.lower()
f = e.capitalize()
g = d.lower().replace('h', 'aa').capitalize()
h = text.split(' ')
h1 = text.split()
i = d.strip() #удаление пробелов
j = len(h1)
k = None1 is None
l = None1 is not None
m = type(d)
n = type(None1)
print('d =', d)
print('e =', e)
print('f =', f)
print('g =', g)
print('h =', h)
print('h1 =', h1)
print('i =', i)
print('j =', j)
print('k =', k)
print('l =', l)
print('m =', m)
print('n =', n)
